version: '3.0'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: always
    stdin_open: true
    tty: true
    ports:
        - "9000:9000/tcp"
    environment:
        - TZ=Europe/Warsaw
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /opt/portainer:/data
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
        - /opt/homeassistant/config:/config
        - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    devices:
        - /dev/ttyUSB0:/dev/ttyUSB0
  octoprint:
    container_name: octoprint
    image: octoprint/octoprint
    volumes:
        - /opt/octoprint:/octoprint
        - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
        - 80:80
    devices:
        - /dev/ttyUSB0:/dev/ttyUSB0
        - /dev/ttyUSB1:/dev/ttyUSB1